# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

figtree <- function(X, h, Q, Y, epsilon, G) {
    .Call(`_TDApplied_figtree`, X, h, Q, Y, epsilon, G)
}

